on:
  push:

name: conda-R-install

jobs:
  conda-R-install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update && \
          sudo apt-get -y install libudunits2-dev libcairo2-dev
        
      - name: setup conda
        uses: s-weigand/setup-conda@v1.0.5
        with:
          activate-conda: true
          update-conda: true
          conda-channels: 'bioconda,conda-forge,defaults'

      - name: install snakemake and run workflow
        run: |
          conda install snakemake=5.16.0
          mkdir -p $HOME/.R
          echo -e 'MAKEFLAGS = -j8' > $HOME/.R/Makevars
          echo 'options(Ncpus = 8)' > $HOME/.Rprofile
          snakemake --use-conda --cores 2

      - name: upload artifact
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: pkg_install_rout
          path: pkg_install.Rout
