on:
  push:
  pull_request:
    branches:
      - master

name: R-install

jobs:
  R-install:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest, r: '4.0'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
      
      - name: Install packages
        run: |
          paths <- .libPaths()
          print(paths)
          (mirror <- getOption("repos"))
          pkgs <- c("dplyr", "ggplot2", "tidyr", "limma", "edgeR",
               "S4Vectors", "DRIMSeq", "SingleCellExperiment", "tximeta", "msigdbr")
          isBiocM <- "BiocManager" %in% installed.packages()[, 1]
          if (!isBiocM) {
            install.packages("BiocManager", repos = "http://cran.rstudio.com/",
                             lib = .libPaths()[1])
          }
          isInstalled <- pkgs %in% installed.packages(lib.loc = .libPaths()[1])[, 1]
          BiocManager::install(pkgs[!isInstalled],
                               update = FALSE, dependencies = TRUE,
                               lib = .libPaths()[1], Ncpus = 2L)
          pkg.load <- lapply(pkgs, FUN = function(x) {
            x[!(x %in% installed.packages(.libPaths()[1])[, "Package"])]
          })
          suppressPackageStartupMessages(
            lapply(pkgs, library, character.only = TRUE)
          )
        shell: Rscript {0}
