on:
  push:
  pull_request:
    branches:
      - master

name: R-install

jobs:
  R-install:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: windows-latest, r: 'devel', bioc: 'devel'}
        - { os: macOS-latest, r: 'devel', bioc: 'devel'}
        - { os: macOS-latest, r: 'release', bioc: '3.12'}
        - { os: ubuntu-16.04, r: 'devel', bioc: 'devel', cran: "https://demo.rstudiopm.com/all/__linux__/xenial/latest"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
      
      - name: Install and load packages
        run: |
          install.packages("RCurl")
          library(RCurl)
          install.packages("BiocManager")
          BiocManager::install(version = "${{ matrix.config.bioc }}", ask = FALSE)
          BiocManager::install("BiocCheck")
        shell: Rscript {0}
