on:
  push:
  pull_request:
    branches:
      - master

name: R-install

jobs:
  R-install:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest, r: '4.0'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
      
      - name: Install packages
        run: |
          install.packages(c('remotes', 'BiocManager'))
          print("---")
          (object = remotes:::package_deps('TxDb.Hsapiens.UCSC.hg19.knownGene', repos = c(getOption('repos'), BiocManager::repositories()), type = "both"))
          print("----")
          (object <- remotes:::upgradable_packages(object, upgrade = "default", quiet = FALSE))
          print("-----")
          (unavailable_on_cran <- object$diff == remotes:::UNAVAILABLE & object$is_cran)
          print("----- -")
          (unknown_remotes <- (object$diff == remotes:::UNAVAILABLE | object$diff == remotes:::UNINSTALLED) & !object$is_cran)
          print("----- --")
          (ahead_of_cran <- object$diff == remotes:::AHEAD & object$is_cran)
          print("----- ---")
          (behind <- is.na(object$installed) | object$diff < remotes:::CURRENT)
          print("----- ----")
          (any(object$is_cran & !unavailable_on_cran & behind))
          print("----- -----")
          (r <- object$remote[object$is_cran & behind][[1]])
          print("----- ----- -")
          (object$package[object$is_cran & behind])
          print("----- ----- --")
          install.packages(c("TxDb.Hsapiens.UCSC.hg19.knownGene","IRanges","GenomeInfoDb"), repos = c(getOption('repos'), BiocManager::repositories()), type = "both", dependencies = TRUE)
        shell: Rscript {0}
