on:
  push:
  pull_request:
    branches:
      - master

name: R-install

jobs:
  R-install:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: '4.0'}
          - {os: macOS-latest, r: '4.0'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
      
      - name: Install packages
        run: |
          install.packages('BiocManager')
          BiocManager::install('TxDb.Hsapiens.UCSC.hg19.knownGene')
        shell: Rscript {0}
