on:
  push:
  pull_request:
    branches:
      - master

name: R-install

jobs:
  R-install:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: windows-latest, r: 'devel', bioc: 'devel'}
        - { os: macOS-latest, r: 'devel', bioc: 'devel'}
        - { os: macOS-latest, r: 'release', bioc: '3.12'}
        - { os: ubuntu-16.04, r: 'devel', bioc: 'devel', cran: "https://demo.rstudiopm.com/all/__linux__/xenial/latest"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
      
      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          sudo apt-get update && sudo apt-get -y install libcurl4-openssl-dev
          
      - name: Install and load packages
        run: |
          install.packages("RCurl")
          library(RCurl)
          install.packages("BiocManager")
          BiocManager::install(version = "${{ matrix.config.bioc }}", ask = FALSE)
          BiocManager::install(c("BiocCheck", "UniProt.ws"))
          library(UniProt.ws)
          up <- UniProt.ws(taxId = 9606)
          select(up, keys=c("P31946","P62258"), columns=c("PDB","SEQUENCE"), keytype="UNIPROTKB")
        shell: Rscript {0}

      - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}

